name = "clemens-worker"
main = "src/index.ts"
compatibility_date = "2026-03-21"
workers_dev = true

[vars]
CORS_ORIGIN = "*"

[[d1_databases]]
binding = "DB"
database_name = "db_clemens"
database_id = "9ee3559c-23c7-4c83-8783-6980634a4bd8"

[[r2_buckets]]
binding = "BIBLE_LIBRARY"
bucket_name = "clemens-library"
preview_bucket_name = "clemens-library-preview"
